---
title: "Research Notes for Sanghoon Park"
image: ./media/favicon.ico
comments: false
about:
  template: solana
  links:
    #- text: "{{< fa brands meetup >}} Meetup"
    #  href: https://www.meetup.com/R-Lille/
    - text: "{{< fa brands github >}} GitHub"
      href: https://github.com/pherephobia/Research_notes
    #- text: "{{< fa brands twitter >}} Twitter"
    #  href: https://twitter.com/RLille_RUG
    #- text: "{{< fa brands youtube >}} YouTube"
    #  href: https://www.youtube.com/c/RLille
    #- text: "{{< fa brands slack >}} Slack"
    #  href: https://r-grrr.slack.com/archives/C042K6XB34G
---

I'm a Ph.D. candidate in the Department of Political Science at University of
South Carolina, Columbia. I received a B.A. and M.A. in political science and
international relations from Hankuk University of Foreign Studies' Department of
Political Science and International Relations in 2015 and 2017, respectively.

My research agenda is situated at the nexus of Comparative Politics and
International Relations and focuses on autocrats and institutions' interaction,
emphasizing resource distribution, regime stability, and transitions. I address
how and under what conditions autocrats use their power to perpetuate their
rule. My goal is to shed light on the processes that produce seemingly identical
consequences across democracies and autocracies.
